//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shebarin_Kval
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FitnessEntities : DbContext
    {
        public static FitnessEntities _context;
        public FitnessEntities()
            : base("name=FitnessEntities")
        {
        }
        public static FitnessEntities GetContext()
        {
            if (_context == null)
            {
                _context = new FitnessEntities();
            }
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<exercise_ways> exercise_ways { get; set; }
        public virtual DbSet<fitness_clubs> fitness_clubs { get; set; }
        public virtual DbSet<sports_exercises> sports_exercises { get; set; }
        public virtual DbSet<sports_types> sports_types { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Table_3_View> Table_3_View { get; set; }
    }
}
