//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shebarin_Kval
{
    using System;
    using System.Collections.Generic;
    
    public partial class fitness_clubs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fitness_clubs()
        {
            this.sports_exercises = new HashSet<sports_exercises>();
        }
    
        public int club_id { get; set; }
        public string club_name { get; set; }
        public string address { get; set; }
        public string phone_number { get; set; }
        public string has_pool { get; set; }
        public Nullable<System.DateTime> open_date { get; set; }
        public string site_url { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sports_exercises> sports_exercises { get; set; }
    }
}
